package com.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayPersonProjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonProjectAllPropertiesEquals(DayPersonProject expected, DayPersonProject actual) {
        assertDayPersonProjectAutoGeneratedPropertiesEquals(expected, actual);
        assertDayPersonProjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonProjectAllUpdatablePropertiesEquals(DayPersonProject expected, DayPersonProject actual) {
        assertDayPersonProjectUpdatableFieldsEquals(expected, actual);
        assertDayPersonProjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonProjectAutoGeneratedPropertiesEquals(DayPersonProject expected, DayPersonProject actual) {
        assertThat(actual)
            .as("Verify DayPersonProject auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonProjectUpdatableFieldsEquals(DayPersonProject expected, DayPersonProject actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonProjectUpdatableRelationshipsEquals(DayPersonProject expected, DayPersonProject actual) {
        assertThat(actual)
            .as("Verify DayPersonProject relationships")
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()))
            .satisfies(a -> assertThat(a.getDayPerson()).as("check dayPerson").isEqualTo(expected.getDayPerson()));
    }
}
