package com.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayPlanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanAllPropertiesEquals(DayPlan expected, DayPlan actual) {
        assertDayPlanAutoGeneratedPropertiesEquals(expected, actual);
        assertDayPlanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanAllUpdatablePropertiesEquals(DayPlan expected, DayPlan actual) {
        assertDayPlanUpdatableFieldsEquals(expected, actual);
        assertDayPlanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanAutoGeneratedPropertiesEquals(DayPlan expected, DayPlan actual) {
        assertThat(actual)
            .as("Verify DayPlan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanUpdatableFieldsEquals(DayPlan expected, DayPlan actual) {
        assertThat(actual)
            .as("Verify DayPlan relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanUpdatableRelationshipsEquals(DayPlan expected, DayPlan actual) {
        assertThat(actual)
            .as("Verify DayPlan relationships")
            .satisfies(a -> assertThat(a.getWeek()).as("check week").isEqualTo(expected.getWeek()));
    }
}
