package com.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayPersonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonAllPropertiesEquals(DayPerson expected, DayPerson actual) {
        assertDayPersonAutoGeneratedPropertiesEquals(expected, actual);
        assertDayPersonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonAllUpdatablePropertiesEquals(DayPerson expected, DayPerson actual) {
        assertDayPersonUpdatableFieldsEquals(expected, actual);
        assertDayPersonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonAutoGeneratedPropertiesEquals(DayPerson expected, DayPerson actual) {
        assertThat(actual)
            .as("Verify DayPerson auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonUpdatableFieldsEquals(DayPerson expected, DayPerson actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPersonUpdatableRelationshipsEquals(DayPerson expected, DayPerson actual) {
        assertThat(actual)
            .as("Verify DayPerson relationships")
            .satisfies(a -> assertThat(a.getPerson()).as("check person").isEqualTo(expected.getPerson()))
            .satisfies(a -> assertThat(a.getDayPlan()).as("check dayPlan").isEqualTo(expected.getDayPlan()));
    }
}
