package com.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WeekAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekAllPropertiesEquals(Week expected, Week actual) {
        assertWeekAutoGeneratedPropertiesEquals(expected, actual);
        assertWeekAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekAllUpdatablePropertiesEquals(Week expected, Week actual) {
        assertWeekUpdatableFieldsEquals(expected, actual);
        assertWeekUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekAutoGeneratedPropertiesEquals(Week expected, Week actual) {
        assertThat(actual)
            .as("Verify Week auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekUpdatableFieldsEquals(Week expected, Week actual) {
        assertThat(actual)
            .as("Verify Week relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekUpdatableRelationshipsEquals(Week expected, Week actual) {
        // empty method
    }
}
