package pt.formacao.escola.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisciplinaEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinaEntityAllPropertiesEquals(DisciplinaEntity expected, DisciplinaEntity actual) {
        assertDisciplinaEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDisciplinaEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinaEntityAllUpdatablePropertiesEquals(DisciplinaEntity expected, DisciplinaEntity actual) {
        assertDisciplinaEntityUpdatableFieldsEquals(expected, actual);
        assertDisciplinaEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinaEntityAutoGeneratedPropertiesEquals(DisciplinaEntity expected, DisciplinaEntity actual) {
        assertThat(actual)
            .as("Verify DisciplinaEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinaEntityUpdatableFieldsEquals(DisciplinaEntity expected, DisciplinaEntity actual) {
        assertThat(actual)
            .as("Verify DisciplinaEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCapacity()).as("check capacity").isEqualTo(expected.getCapacity()))
            .satisfies(a -> assertThat(a.getCredits()).as("check credits").isEqualTo(expected.getCredits()))
            .satisfies(a -> assertThat(a.getTeacherName()).as("check teacherName").isEqualTo(expected.getTeacherName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisciplinaEntityUpdatableRelationshipsEquals(DisciplinaEntity expected, DisciplinaEntity actual) {
        assertThat(actual)
            .as("Verify DisciplinaEntity relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
