package pt.formacao.escola.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentEntityAllPropertiesEquals(StudentEntity expected, StudentEntity actual) {
        assertStudentEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentEntityAllUpdatablePropertiesEquals(StudentEntity expected, StudentEntity actual) {
        assertStudentEntityUpdatableFieldsEquals(expected, actual);
        assertStudentEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentEntityAutoGeneratedPropertiesEquals(StudentEntity expected, StudentEntity actual) {
        assertThat(actual)
            .as("Verify StudentEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentEntityUpdatableFieldsEquals(StudentEntity expected, StudentEntity actual) {
        assertThat(actual)
            .as("Verify StudentEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getAge()).as("check age").isEqualTo(expected.getAge()))
            .satisfies(a -> assertThat(a.getGenre()).as("check genre").isEqualTo(expected.getGenre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentEntityUpdatableRelationshipsEquals(StudentEntity expected, StudentEntity actual) {
        assertThat(actual)
            .as("Verify StudentEntity relationships")
            .satisfies(a -> assertThat(a.getStudentAddress()).as("check studentAddress").isEqualTo(expected.getStudentAddress()))
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
