package com.mycompany.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayPlanEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanEntityAllPropertiesEquals(DayPlanEntity expected, DayPlanEntity actual) {
        assertDayPlanEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDayPlanEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanEntityAllUpdatablePropertiesEquals(DayPlanEntity expected, DayPlanEntity actual) {
        assertDayPlanEntityUpdatableFieldsEquals(expected, actual);
        assertDayPlanEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanEntityAutoGeneratedPropertiesEquals(DayPlanEntity expected, DayPlanEntity actual) {
        assertThat(actual)
            .as("Verify DayPlanEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanEntityUpdatableFieldsEquals(DayPlanEntity expected, DayPlanEntity actual) {
        assertThat(actual)
            .as("Verify DayPlanEntity relevant properties")
            .satisfies(a -> assertThat(a.getDate()).as("check date").isEqualTo(expected.getDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayPlanEntityUpdatableRelationshipsEquals(DayPlanEntity expected, DayPlanEntity actual) {
        assertThat(actual)
            .as("Verify DayPlanEntity relationships")
            .satisfies(a -> assertThat(a.getWeek()).as("check week").isEqualTo(expected.getWeek()));
    }
}
