package com.mycompany.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayUserProjectEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserProjectEntityAllPropertiesEquals(DayUserProjectEntity expected, DayUserProjectEntity actual) {
        assertDayUserProjectEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDayUserProjectEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserProjectEntityAllUpdatablePropertiesEquals(DayUserProjectEntity expected, DayUserProjectEntity actual) {
        assertDayUserProjectEntityUpdatableFieldsEquals(expected, actual);
        assertDayUserProjectEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserProjectEntityAutoGeneratedPropertiesEquals(DayUserProjectEntity expected, DayUserProjectEntity actual) {
        assertThat(actual)
            .as("Verify DayUserProjectEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserProjectEntityUpdatableFieldsEquals(DayUserProjectEntity expected, DayUserProjectEntity actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserProjectEntityUpdatableRelationshipsEquals(DayUserProjectEntity expected, DayUserProjectEntity actual) {
        assertThat(actual)
            .as("Verify DayUserProjectEntity relationships")
            .satisfies(a -> assertThat(a.getDayUser()).as("check dayUser").isEqualTo(expected.getDayUser()))
            .satisfies(a -> assertThat(a.getProject()).as("check project").isEqualTo(expected.getProject()));
    }
}
