package com.mycompany.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DayUserEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserEntityAllPropertiesEquals(DayUserEntity expected, DayUserEntity actual) {
        assertDayUserEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertDayUserEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserEntityAllUpdatablePropertiesEquals(DayUserEntity expected, DayUserEntity actual) {
        assertDayUserEntityUpdatableFieldsEquals(expected, actual);
        assertDayUserEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserEntityAutoGeneratedPropertiesEquals(DayUserEntity expected, DayUserEntity actual) {
        assertThat(actual)
            .as("Verify DayUserEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserEntityUpdatableFieldsEquals(DayUserEntity expected, DayUserEntity actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDayUserEntityUpdatableRelationshipsEquals(DayUserEntity expected, DayUserEntity actual) {
        assertThat(actual)
            .as("Verify DayUserEntity relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a -> assertThat(a.getDayPlan()).as("check dayPlan").isEqualTo(expected.getDayPlan()));
    }
}
