package com.mycompany.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProjectEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectEntityAllPropertiesEquals(ProjectEntity expected, ProjectEntity actual) {
        assertProjectEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertProjectEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectEntityAllUpdatablePropertiesEquals(ProjectEntity expected, ProjectEntity actual) {
        assertProjectEntityUpdatableFieldsEquals(expected, actual);
        assertProjectEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectEntityAutoGeneratedPropertiesEquals(ProjectEntity expected, ProjectEntity actual) {
        assertThat(actual)
            .as("Verify ProjectEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectEntityUpdatableFieldsEquals(ProjectEntity expected, ProjectEntity actual) {
        assertThat(actual)
            .as("Verify ProjectEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProjectEntityUpdatableRelationshipsEquals(ProjectEntity expected, ProjectEntity actual) {
        // empty method
    }
}
