package com.mycompany.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TaskEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskEntityAllPropertiesEquals(TaskEntity expected, TaskEntity actual) {
        assertTaskEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertTaskEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskEntityAllUpdatablePropertiesEquals(TaskEntity expected, TaskEntity actual) {
        assertTaskEntityUpdatableFieldsEquals(expected, actual);
        assertTaskEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskEntityAutoGeneratedPropertiesEquals(TaskEntity expected, TaskEntity actual) {
        assertThat(actual)
            .as("Verify TaskEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskEntityUpdatableFieldsEquals(TaskEntity expected, TaskEntity actual) {
        assertThat(actual)
            .as("Verify TaskEntity relevant properties")
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTaskEntityUpdatableRelationshipsEquals(TaskEntity expected, TaskEntity actual) {
        assertThat(actual)
            .as("Verify TaskEntity relationships")
            .satisfies(a -> assertThat(a.getDayUserProject()).as("check dayUserProject").isEqualTo(expected.getDayUserProject()));
    }
}
