package com.mycompany.weeklyplanning.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WeekEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekEntityAllPropertiesEquals(WeekEntity expected, WeekEntity actual) {
        assertWeekEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertWeekEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekEntityAllUpdatablePropertiesEquals(WeekEntity expected, WeekEntity actual) {
        assertWeekEntityUpdatableFieldsEquals(expected, actual);
        assertWeekEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekEntityAutoGeneratedPropertiesEquals(WeekEntity expected, WeekEntity actual) {
        assertThat(actual)
            .as("Verify WeekEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekEntityUpdatableFieldsEquals(WeekEntity expected, WeekEntity actual) {
        assertThat(actual)
            .as("Verify WeekEntity relevant properties")
            .satisfies(a -> assertThat(a.getLabel()).as("check label").isEqualTo(expected.getLabel()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWeekEntityUpdatableRelationshipsEquals(WeekEntity expected, WeekEntity actual) {
        // empty method
    }
}
