package pt.formacao.escola.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourseEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEntityAllPropertiesEquals(CourseEntity expected, CourseEntity actual) {
        assertCourseEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertCourseEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEntityAllUpdatablePropertiesEquals(CourseEntity expected, CourseEntity actual) {
        assertCourseEntityUpdatableFieldsEquals(expected, actual);
        assertCourseEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEntityAutoGeneratedPropertiesEquals(CourseEntity expected, CourseEntity actual) {
        assertThat(actual)
            .as("Verify CourseEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEntityUpdatableFieldsEquals(CourseEntity expected, CourseEntity actual) {
        assertThat(actual)
            .as("Verify CourseEntity relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourseEntityUpdatableRelationshipsEquals(CourseEntity expected, CourseEntity actual) {
        // empty method
    }
}
