package pt.formacao.escola.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GradeEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeEntityAllPropertiesEquals(GradeEntity expected, GradeEntity actual) {
        assertGradeEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertGradeEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeEntityAllUpdatablePropertiesEquals(GradeEntity expected, GradeEntity actual) {
        assertGradeEntityUpdatableFieldsEquals(expected, actual);
        assertGradeEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeEntityAutoGeneratedPropertiesEquals(GradeEntity expected, GradeEntity actual) {
        assertThat(actual)
            .as("Verify GradeEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeEntityUpdatableFieldsEquals(GradeEntity expected, GradeEntity actual) {
        assertThat(actual)
            .as("Verify GradeEntity relevant properties")
            .satisfies(a -> assertThat(a.getValue()).as("check value").isEqualTo(expected.getValue()))
            .satisfies(a -> assertThat(a.getFinished()).as("check finished").isEqualTo(expected.getFinished()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeEntityUpdatableRelationshipsEquals(GradeEntity expected, GradeEntity actual) {
        assertThat(actual)
            .as("Verify GradeEntity relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()))
            .satisfies(a -> assertThat(a.getDisciplina()).as("check disciplina").isEqualTo(expected.getDisciplina()));
    }
}
