package pt.formacao.escola.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentAddressEntityAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAddressEntityAllPropertiesEquals(StudentAddressEntity expected, StudentAddressEntity actual) {
        assertStudentAddressEntityAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentAddressEntityAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAddressEntityAllUpdatablePropertiesEquals(StudentAddressEntity expected, StudentAddressEntity actual) {
        assertStudentAddressEntityUpdatableFieldsEquals(expected, actual);
        assertStudentAddressEntityUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAddressEntityAutoGeneratedPropertiesEquals(StudentAddressEntity expected, StudentAddressEntity actual) {
        assertThat(actual)
            .as("Verify StudentAddressEntity auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAddressEntityUpdatableFieldsEquals(StudentAddressEntity expected, StudentAddressEntity actual) {
        assertThat(actual)
            .as("Verify StudentAddressEntity relevant properties")
            .satisfies(a -> assertThat(a.getAdressLine()).as("check adressLine").isEqualTo(expected.getAdressLine()))
            .satisfies(a -> assertThat(a.getPostalCode()).as("check postalCode").isEqualTo(expected.getPostalCode()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAddressEntityUpdatableRelationshipsEquals(StudentAddressEntity expected, StudentAddressEntity actual) {
        // empty method
    }
}
